"""Sandboxed, content-addressed local object storage (SEC-006, SEC-007, ADR-007).

Objects are stored immutably under `<root>/sha256/<aa>/<bb>/<hex>`. Keys are
generated by the store, never taken from user input, and every resolved path
is checked to stay inside the configured root.
"""

from __future__ import annotations

import hashlib
import os
import re
import tempfile
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Protocol

from fastapi import status

from research_api.config import get_settings
from research_api.platform.errors import DomainError

_KEY = re.compile(r"^sha256/[0-9a-f]{2}/[0-9a-f]{2}/[0-9a-f]{64}$")


class StorageError(DomainError):
    code = "storage_error"


class UnsupportedMediaError(DomainError):
    status_code = status.HTTP_415_UNSUPPORTED_MEDIA_TYPE
    code = "unsupported_media"


class TooLargeError(DomainError):
    status_code = status.HTTP_413_CONTENT_TOO_LARGE
    code = "too_large"


@dataclass(frozen=True)
class StoredObject:
    key: str
    sha256: str
    byte_size: int


class ObjectStore(Protocol):
    def put(self, data: bytes) -> StoredObject: ...
    def read(self, key: str) -> bytes: ...
    def exists(self, key: str) -> bool: ...


class LocalObjectStore:
    def __init__(self, root: Path) -> None:
        self.root = root.resolve()
        self.root.mkdir(parents=True, exist_ok=True)

    def _path(self, key: str) -> Path:
        if not _KEY.match(key):
            raise StorageError("invalid storage key")
        path = (self.root / key).resolve()
        if not path.is_relative_to(self.root):
            raise StorageError("storage key escapes the storage root")
        return path

    def put(self, data: bytes) -> StoredObject:
        digest = hashlib.sha256(data).hexdigest()
        key = f"sha256/{digest[:2]}/{digest[2:4]}/{digest}"
        path = self._path(key)
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            fd, tmp = tempfile.mkstemp(dir=path.parent)
            try:
                with os.fdopen(fd, "wb") as fh:
                    fh.write(data)
                os.chmod(tmp, 0o444)
                os.replace(tmp, path)
            except BaseException:
                Path(tmp).unlink(missing_ok=True)
                raise
        return StoredObject(key=key, sha256=digest, byte_size=len(data))

    def read(self, key: str) -> bytes:
        path = self._path(key)
        if not path.exists():
            raise StorageError("object not found in storage", key=key)
        data = path.read_bytes()
        if hashlib.sha256(data).hexdigest() != key.rsplit("/", 1)[1]:
            raise StorageError("stored object failed its integrity check", key=key)
        return data

    def exists(self, key: str) -> bool:
        return self._path(key).exists()


@lru_cache(maxsize=1)
def get_store() -> ObjectStore:
    return LocalObjectStore(get_settings().storage_root)


# --- upload validation (SEC-006) ---

ALLOWED_MEDIA: dict[str, str] = {
    "application/pdf": "PDF",
    "text/plain": "LOCAL_TEXT",
    "image/png": "IMAGE",
    "image/jpeg": "IMAGE",
    "application/epub+zip": "EPUB",
}


def sniff_media_type(data: bytes) -> str | None:
    """Identify content from its bytes; the client-declared type is never trusted."""
    if data.startswith(b"%PDF-"):
        return "application/pdf"
    if data.startswith(b"\x89PNG\r\n\x1a\n"):
        return "image/png"
    if data.startswith(b"\xff\xd8\xff"):
        return "image/jpeg"
    if data.startswith(b"PK\x03\x04") and data[30:58] == b"mimetypeapplication/epub+zip":
        return "application/epub+zip"
    if b"\x00" not in data:
        try:
            data.decode("utf-8")
        except UnicodeDecodeError:
            return None
        return "text/plain"
    return None


def validate_upload(data: bytes, *, allowed: frozenset[str] | None = None) -> str:
    """Return the sniffed media type or raise. Empty and oversized uploads are rejected."""
    limit = get_settings().max_upload_bytes
    if not data:
        raise UnsupportedMediaError("empty upload")
    if len(data) > limit:
        raise TooLargeError(f"upload exceeds {limit} bytes", limit=limit)
    media = sniff_media_type(data)
    permitted = allowed or frozenset(ALLOWED_MEDIA)
    if media is None or media not in permitted:
        raise UnsupportedMediaError("file type is not accepted", accepted=sorted(permitted))
    return media


def safe_filename(name: str | None) -> str | None:
    """Display-only filename: strip any path components and control characters."""
    if not name:
        return None
    base = name.replace("\\", "/").rsplit("/", 1)[-1]
    cleaned = "".join(ch for ch in base if ch.isprintable() and ch not in '<>:"|?*').strip(" .")
    return cleaned[:255] or None
