"""AI gateway: per-project AI policy and the append-only disclosure/usage log (PRD §54, §64, ADR-010).

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-24 19:01:19.856359
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_requests",
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("task", sa.String(length=100), nullable=False),
        sa.Column("template_version", sa.String(length=40), nullable=False),
        sa.Column("profile", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_kind", sa.String(length=60), nullable=True),
        sa.Column("disclosure_reason", sa.Text(), nullable=False),
        sa.Column("sensitivity", sa.String(length=20), nullable=False),
        sa.Column("entity_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("outbound_chars", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("served_by_fallback", sa.Boolean(), nullable=False),
        sa.Column("provider_request_id", sa.String(length=200), nullable=True),
        sa.Column("principal_id", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_requests")),
    )
    op.create_index(op.f("ix_ai_requests_project_id"), "ai_requests", ["project_id"], unique=False)
    op.create_table(
        "project_ai_policies",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("cloud_consent", sa.Boolean(), nullable=False),
        sa.Column("allowed_profiles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preferred_profile", sa.String(length=100), nullable=True),
        sa.Column("project_budget_usd", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("task_budget_usd", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("updated_by_id", sa.String(length=200), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_project_ai_policies_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("project_id", name=op.f("pk_project_ai_policies")),
    )
    op.execute(
        "CREATE TRIGGER ai_requests_append_only BEFORE UPDATE OR DELETE ON ai_requests "
        "FOR EACH ROW EXECUTE FUNCTION reject_mutation_of_append_only()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS ai_requests_append_only ON ai_requests")
    op.drop_table("project_ai_policies")
    op.drop_index(op.f("ix_ai_requests_project_id"), table_name="ai_requests")
    op.drop_table("ai_requests")
    # ### end Alembic commands ###
