"""Research plans (versioned), append-only search audit and sufficiency, web-origin source leads (ADR-012).

Additive only: new tables and nullable/defaulted columns; no existing data changes.

Revision ID: 0009
Revises: 0008
Create Date: 2026-09-24 19:25:12.534974
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

PROTECT_PLAN = """
CREATE OR REPLACE FUNCTION protect_research_plan() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'research plans are versioned and cannot be deleted';
    END IF;
    IF (to_jsonb(NEW) - 'status') <> (to_jsonb(OLD) - 'status')
        OR NOT (OLD.status = 'ACTIVE' AND NEW.status = 'SUPERSEDED') THEN
        RAISE EXCEPTION 'research plan versions are immutable; only ACTIVE -> SUPERSEDED is allowed';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_plans",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("series_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("decision_served", sa.Text(), nullable=False),
        sa.Column("question_type", sa.String(length=30), nullable=False),
        sa.Column("risk_impact", sa.Text(), nullable=False),
        sa.Column("desired_evidence_types", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("languages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tracks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sufficiency_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("max_web_searches", sa.Integer(), nullable=True),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_research_plans_project_id_projects")),
        sa.ForeignKeyConstraint(
            ["supersedes_id"], ["research_plans.id"], name=op.f("fk_research_plans_supersedes_id_research_plans")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_research_plans")),
        sa.UniqueConstraint("project_id", "series_id", "version_number", name=op.f("uq_research_plans_project_id")),
    )
    op.create_index(op.f("ix_research_plans_project_id"), "research_plans", ["project_id"], unique=False)
    op.create_index(op.f("ix_research_plans_series_id"), "research_plans", ["series_id"], unique=False)
    op.create_table(
        "search_records",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("track", sa.String(length=30), nullable=True),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("queries", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("languages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("outcome", sa.String(length=40), nullable=False),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("exclusions", sa.Text(), nullable=True),
        sa.Column("ai_request_id", sa.Uuid(), nullable=True),
        sa.Column("actor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("performed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["research_plans.id"], name=op.f("fk_search_records_plan_id_research_plans")
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_search_records_project_id_projects")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_records")),
    )
    op.create_index(op.f("ix_search_records_plan_id"), "search_records", ["plan_id"], unique=False)
    op.create_index(op.f("ix_search_records_project_id"), "search_records", ["project_id"], unique=False)
    op.create_table(
        "sufficiency_assessments",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("decision_served", sa.Text(), nullable=False),
        sa.Column("result", sa.String(length=40), nullable=False),
        sa.Column("considerations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("recommend_experiment", sa.Boolean(), nullable=False),
        sa.Column("signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assessed_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["research_plans.id"], name=op.f("fk_sufficiency_assessments_plan_id_research_plans")
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_sufficiency_assessments_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sufficiency_assessments")),
    )
    op.create_index(op.f("ix_sufficiency_assessments_plan_id"), "sufficiency_assessments", ["plan_id"], unique=False)
    op.create_index(
        op.f("ix_sufficiency_assessments_project_id"), "sufficiency_assessments", ["project_id"], unique=False
    )
    op.add_column(
        "source_leads", sa.Column("origin", sa.String(length=30), server_default="RESEARCHER_MEMORY", nullable=False)
    )
    op.add_column("source_leads", sa.Column("url", sa.Text(), nullable=True))
    op.add_column("source_leads", sa.Column("title", sa.Text(), nullable=True))
    op.add_column("source_leads", sa.Column("search_record_id", sa.Uuid(), nullable=True))
    op.add_column("source_leads", sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f("ix_source_leads_search_record_id"), "source_leads", ["search_record_id"], unique=False)
    for table in ("search_records", "sufficiency_assessments"):
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION reject_mutation_of_append_only()"
        )
    op.execute(PROTECT_PLAN)
    op.execute(
        "CREATE TRIGGER research_plans_versioned BEFORE UPDATE OR DELETE ON research_plans "
        "FOR EACH ROW EXECUTE FUNCTION protect_research_plan()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS research_plans_versioned ON research_plans")
    op.execute("DROP FUNCTION IF EXISTS protect_research_plan()")
    for table in ("search_records", "sufficiency_assessments"):
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.drop_index(op.f("ix_source_leads_search_record_id"), table_name="source_leads")
    op.drop_column("source_leads", "provenance")
    op.drop_column("source_leads", "search_record_id")
    op.drop_column("source_leads", "title")
    op.drop_column("source_leads", "url")
    op.drop_column("source_leads", "origin")
    op.drop_index(op.f("ix_sufficiency_assessments_project_id"), table_name="sufficiency_assessments")
    op.drop_index(op.f("ix_sufficiency_assessments_plan_id"), table_name="sufficiency_assessments")
    op.drop_table("sufficiency_assessments")
    op.drop_index(op.f("ix_search_records_project_id"), table_name="search_records")
    op.drop_index(op.f("ix_search_records_plan_id"), table_name="search_records")
    op.drop_table("search_records")
    op.drop_index(op.f("ix_research_plans_series_id"), table_name="research_plans")
    op.drop_index(op.f("ix_research_plans_project_id"), table_name="research_plans")
    op.drop_table("research_plans")
    # ### end Alembic commands ###
