"""Append-only audit of AI tool calls, refused ones included (PRD §47, §53, ADR-013).

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-24 21:14:15.994037
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_tool_calls",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("ai_request_id", sa.Uuid(), nullable=True),
        sa.Column("tool", sa.String(length=80), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("output_sha256", sa.String(length=64), nullable=True),
        sa.Column("principal_id", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_tool_calls")),
    )
    op.create_index(op.f("ix_ai_tool_calls_job_id"), "ai_tool_calls", ["job_id"], unique=False)
    op.create_index(op.f("ix_ai_tool_calls_project_id"), "ai_tool_calls", ["project_id"], unique=False)
    op.execute(
        "CREATE TRIGGER ai_tool_calls_append_only BEFORE UPDATE OR DELETE ON ai_tool_calls "
        "FOR EACH ROW EXECUTE FUNCTION reject_mutation_of_append_only()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS ai_tool_calls_append_only ON ai_tool_calls")
    op.drop_index(op.f("ix_ai_tool_calls_project_id"), table_name="ai_tool_calls")
    op.drop_index(op.f("ix_ai_tool_calls_job_id"), table_name="ai_tool_calls")
    op.drop_table("ai_tool_calls")
    # ### end Alembic commands ###
