"""AI reliability registry: append-only evaluation results per model and dimension (PRD §52, ADR-014).

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-24 21:20:31.778218
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_evaluations",
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("dimension", sa.String(length=60), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("comparator", sa.String(length=2), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("sample_size", sa.Integer(), nullable=False),
        sa.Column("method", sa.String(length=30), nullable=False),
        sa.Column("fixture_set", sa.String(length=80), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recorded_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_evaluations")),
    )
    op.create_index(op.f("ix_ai_evaluations_dimension"), "ai_evaluations", ["dimension"], unique=False)
    op.create_index(op.f("ix_ai_evaluations_model"), "ai_evaluations", ["model"], unique=False)
    op.create_index(op.f("ix_ai_evaluations_provider"), "ai_evaluations", ["provider"], unique=False)
    op.create_index(op.f("ix_ai_evaluations_run_id"), "ai_evaluations", ["run_id"], unique=False)
    op.execute(
        "CREATE TRIGGER ai_evaluations_append_only BEFORE UPDATE OR DELETE ON ai_evaluations "
        "FOR EACH ROW EXECUTE FUNCTION reject_mutation_of_append_only()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS ai_evaluations_append_only ON ai_evaluations")
    op.drop_index(op.f("ix_ai_evaluations_run_id"), table_name="ai_evaluations")
    op.drop_index(op.f("ix_ai_evaluations_provider"), table_name="ai_evaluations")
    op.drop_index(op.f("ix_ai_evaluations_model"), table_name="ai_evaluations")
    op.drop_index(op.f("ix_ai_evaluations_dimension"), table_name="ai_evaluations")
    op.drop_table("ai_evaluations")
    # ### end Alembic commands ###
