"""Design requirements (versioned) and design concepts with requirement coverage (PRD §32, ADR-015).

Additive only: new tables. Requirement text is protected by a trigger (a revision
appends a version); concepts cannot be deleted, so rejected designs stay in history.

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-24 21:34:39.596558
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

PROTECT_REQUIREMENT = """
CREATE OR REPLACE FUNCTION protect_design_requirement() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'design requirements are versioned and cannot be deleted';
    END IF;
    IF (to_jsonb(NEW) - 'status') <> (to_jsonb(OLD) - 'status')
        OR NOT (
            (OLD.status = 'PROPOSED' AND NEW.status IN ('ACTIVE', 'SUPERSEDED', 'WITHDRAWN'))
            OR (OLD.status = 'ACTIVE' AND NEW.status IN ('SUPERSEDED', 'WITHDRAWN'))
        ) THEN
        RAISE EXCEPTION 'design requirement versions are immutable; only status moves forward';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

KEEP_CONCEPT = """
CREATE OR REPLACE FUNCTION keep_design_concept() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'design concepts stay in history and cannot be deleted';
END;
$$ LANGUAGE plpgsql;
"""

revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "design_concepts",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("origin", sa.String(length=30), nullable=False),
        sa.Column("origin_reference", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("hypothesis_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mechanism_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("derived_from_concept_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rejection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("selection", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_design_concepts_project_id_projects")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_concepts")),
    )
    op.create_index(op.f("ix_design_concepts_project_id"), "design_concepts", ["project_id"], unique=False)
    op.create_index(op.f("ix_design_concepts_status"), "design_concepts", ["status"], unique=False)
    op.create_table(
        "design_requirements",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("series_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("traces", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_design_requirements_project_id_projects")
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["design_requirements.id"],
            name=op.f("fk_design_requirements_supersedes_id_design_requirements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_design_requirements")),
        sa.UniqueConstraint("series_id", "version_number", name=op.f("uq_design_requirements_series_id")),
    )
    op.create_index(op.f("ix_design_requirements_project_id"), "design_requirements", ["project_id"], unique=False)
    op.create_index(op.f("ix_design_requirements_series_id"), "design_requirements", ["series_id"], unique=False)
    op.create_index(op.f("ix_design_requirements_status"), "design_requirements", ["status"], unique=False)
    op.create_table(
        "design_concept_coverage",
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_series_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("coverage", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["concept_id"], ["design_concepts.id"], name=op.f("fk_design_concept_coverage_concept_id_design_concepts")
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["design_requirements.id"],
            name=op.f("fk_design_concept_coverage_requirement_id_design_requirements"),
        ),
        sa.PrimaryKeyConstraint("concept_id", "requirement_series_id", name=op.f("pk_design_concept_coverage")),
    )
    op.execute(PROTECT_REQUIREMENT)
    op.execute(
        "CREATE TRIGGER design_requirements_versioned BEFORE UPDATE OR DELETE ON design_requirements "
        "FOR EACH ROW EXECUTE FUNCTION protect_design_requirement()"
    )
    op.execute(KEEP_CONCEPT)
    op.execute(
        "CREATE TRIGGER design_concepts_kept BEFORE DELETE ON design_concepts "
        "FOR EACH ROW EXECUTE FUNCTION keep_design_concept()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS design_concepts_kept ON design_concepts")
    op.execute("DROP FUNCTION IF EXISTS keep_design_concept()")
    op.execute("DROP TRIGGER IF EXISTS design_requirements_versioned ON design_requirements")
    op.execute("DROP FUNCTION IF EXISTS protect_design_requirement()")
    op.drop_table("design_concept_coverage")
    op.drop_index(op.f("ix_design_requirements_status"), table_name="design_requirements")
    op.drop_index(op.f("ix_design_requirements_series_id"), table_name="design_requirements")
    op.drop_index(op.f("ix_design_requirements_project_id"), table_name="design_requirements")
    op.drop_table("design_requirements")
    op.drop_index(op.f("ix_design_concepts_status"), table_name="design_concepts")
    op.drop_index(op.f("ix_design_concepts_project_id"), table_name="design_concepts")
    op.drop_table("design_concepts")
    # ### end Alembic commands ###
