"""Learning reviews, local knowledge items (versioned) and labelled cross-project reuse (ADR-017).

Additive only: new tables. Learning reviews, knowledge versions and reuses are append-only;
knowledge items cannot be deleted (keep_research_record from 0013).

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-24 21:59:28.001949
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

APPEND_ONLY = ("learning_reviews", "knowledge_versions", "knowledge_reuses")

revision: str = "0014"
down_revision: str | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "knowledge_items",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("stage", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("contexts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("evidence_basis", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contrary_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contrary_evidence_searched", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.String(length=30), nullable=False),
        sa.Column("temporal_profile", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revalidation_interval_days", sa.Integer(), nullable=True),
        sa.Column("source_version", sa.Text(), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_knowledge_items_project_id_projects")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_items")),
    )
    op.create_index(op.f("ix_knowledge_items_project_id"), "knowledge_items", ["project_id"], unique=False)
    op.create_index(op.f("ix_knowledge_items_stage"), "knowledge_items", ["stage"], unique=False)
    op.create_index(op.f("ix_knowledge_items_status"), "knowledge_items", ["status"], unique=False)
    op.create_table(
        "knowledge_reuses",
        sa.Column("knowledge_item_id", sa.Uuid(), nullable=False),
        sa.Column("knowledge_version", sa.Integer(), nullable=False),
        sa.Column("target_project_id", sa.Uuid(), nullable=False),
        sa.Column("transferability", sa.String(length=30), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("differences", sa.Text(), nullable=True),
        sa.Column("assessed_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_item_id"],
            ["knowledge_items.id"],
            name=op.f("fk_knowledge_reuses_knowledge_item_id_knowledge_items"),
        ),
        sa.ForeignKeyConstraint(
            ["target_project_id"], ["projects.id"], name=op.f("fk_knowledge_reuses_target_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_reuses")),
    )
    op.create_index(
        op.f("ix_knowledge_reuses_knowledge_item_id"), "knowledge_reuses", ["knowledge_item_id"], unique=False
    )
    op.create_index(
        op.f("ix_knowledge_reuses_target_project_id"), "knowledge_reuses", ["target_project_id"], unique=False
    )
    op.create_table(
        "knowledge_versions",
        sa.Column("knowledge_item_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change", sa.String(length=30), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("gate_evaluation_id", sa.Uuid(), nullable=True),
        sa.Column("actor", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["knowledge_item_id"],
            ["knowledge_items.id"],
            name=op.f("fk_knowledge_versions_knowledge_item_id_knowledge_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_knowledge_versions")),
        sa.UniqueConstraint(
            "knowledge_item_id", "version_number", name=op.f("uq_knowledge_versions_knowledge_item_id")
        ),
    )
    op.create_index(
        op.f("ix_knowledge_versions_knowledge_item_id"), "knowledge_versions", ["knowledge_item_id"], unique=False
    )
    op.create_table(
        "learning_reviews",
        sa.Column("experiment_id", sa.Uuid(), nullable=False),
        sa.Column("learned", sa.Text(), nullable=False),
        sa.Column("hypothesis_effect", sa.Text(), nullable=False),
        sa.Column("surprises", sa.Text(), nullable=True),
        sa.Column("limitations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("validity_threats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("next_steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reviewed_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"], ["experiments.id"], name=op.f("fk_learning_reviews_experiment_id_experiments")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_reviews")),
    )
    op.create_index(op.f("ix_learning_reviews_experiment_id"), "learning_reviews", ["experiment_id"], unique=False)
    for table in APPEND_ONLY:
        op.execute(
            f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION reject_mutation_of_append_only()"
        )
    op.execute(
        "CREATE TRIGGER knowledge_items_kept BEFORE DELETE ON knowledge_items "
        "FOR EACH ROW EXECUTE FUNCTION keep_research_record()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS knowledge_items_kept ON knowledge_items")
    for table in APPEND_ONLY:
        op.execute(f"DROP TRIGGER IF EXISTS {table}_append_only ON {table}")
    op.drop_index(op.f("ix_learning_reviews_experiment_id"), table_name="learning_reviews")
    op.drop_table("learning_reviews")
    op.drop_index(op.f("ix_knowledge_versions_knowledge_item_id"), table_name="knowledge_versions")
    op.drop_table("knowledge_versions")
    op.drop_index(op.f("ix_knowledge_reuses_target_project_id"), table_name="knowledge_reuses")
    op.drop_index(op.f("ix_knowledge_reuses_knowledge_item_id"), table_name="knowledge_reuses")
    op.drop_table("knowledge_reuses")
    op.drop_index(op.f("ix_knowledge_items_status"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_stage"), table_name="knowledge_items")
    op.drop_index(op.f("ix_knowledge_items_project_id"), table_name="knowledge_items")
    op.drop_table("knowledge_items")
    # ### end Alembic commands ###
