"""Canonical terminology, versioned (PRD §36, ADR-018).

Additive only: one new table. Term content is immutable; only forward status moves (with the
approver stamped on approval) are allowed, and rows cannot be deleted.

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-24 22:09:42.621797
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

PROTECT_TERM = """
CREATE OR REPLACE FUNCTION protect_term() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'terms are versioned and cannot be deleted';
    END IF;
    IF (to_jsonb(NEW) - 'status' - 'approved_by' - 'approved_at')
            <> (to_jsonb(OLD) - 'status' - 'approved_by' - 'approved_at')
        OR NOT (
            (OLD.status = 'PROPOSED' AND NEW.status IN ('APPROVED', 'REJECTED', 'SUPERSEDED'))
            OR (OLD.status = 'APPROVED' AND NEW.status = 'SUPERSEDED')
        )
        OR (OLD.approved_by IS NOT NULL AND NEW.approved_by IS DISTINCT FROM OLD.approved_by) THEN
        RAISE EXCEPTION 'term versions are immutable; only status moves forward';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "terms",
        sa.Column("series_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.Uuid(), nullable=True),
        sa.Column("term", sa.Text(), nullable=False),
        sa.Column("original_language", sa.String(length=5), nullable=False),
        sa.Column("domain", sa.Text(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("translations", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("alternatives", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("retain_original", sa.Boolean(), nullable=False),
        sa.Column("source_authority", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("approved_by", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["supersedes_id"], ["terms.id"], name=op.f("fk_terms_supersedes_id_terms")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_terms")),
        sa.UniqueConstraint("series_id", "version_number", name=op.f("uq_terms_series_id")),
    )
    op.create_index(op.f("ix_terms_domain"), "terms", ["domain"], unique=False)
    op.create_index(op.f("ix_terms_series_id"), "terms", ["series_id"], unique=False)
    op.create_index(op.f("ix_terms_status"), "terms", ["status"], unique=False)
    op.execute(PROTECT_TERM)
    op.execute(
        "CREATE TRIGGER terms_versioned BEFORE UPDATE OR DELETE ON terms FOR EACH ROW EXECUTE FUNCTION protect_term()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS terms_versioned ON terms")
    op.execute("DROP FUNCTION IF EXISTS protect_term()")
    op.drop_index(op.f("ix_terms_status"), table_name="terms")
    op.drop_index(op.f("ix_terms_series_id"), table_name="terms")
    op.drop_index(op.f("ix_terms_domain"), table_name="terms")
    op.drop_table("terms")
    # ### end Alembic commands ###
