"""Project Closure Gate: closures reference their gate evaluation and approval (ADR-019).

Additive only: two nullable columns; existing closures keep NULL (closed before the gate existed).

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-24 22:16:28.720415
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project_closures", sa.Column("gate_evaluation_id", sa.Uuid(), nullable=True))
    op.add_column("project_closures", sa.Column("approval_id", sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project_closures", "approval_id")
    op.drop_column("project_closures", "gate_evaluation_id")
    # ### end Alembic commands ###
