"""Outputs and immutable output versions (PRD §37, ADR-020).

Additive only: two new tables. Version content is immutable; only DRAFT -> APPROVED/SUPERSEDED and
APPROVED -> SUPERSEDED status moves (with the approval id set on approval) are allowed.

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-24 22:34:43.723568
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

PROTECT_VERSION = """
CREATE OR REPLACE FUNCTION protect_output_version() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'output versions are kept and cannot be deleted';
    END IF;
    IF (to_jsonb(NEW) - 'status' - 'approval_id') <> (to_jsonb(OLD) - 'status' - 'approval_id')
        OR NOT (
            (OLD.status = 'DRAFT' AND NEW.status IN ('APPROVED', 'SUPERSEDED'))
            OR (OLD.status = 'APPROVED' AND NEW.status = 'SUPERSEDED')
        )
        OR (OLD.approval_id IS NOT NULL AND NEW.approval_id IS DISTINCT FROM OLD.approval_id) THEN
        RAISE EXCEPTION 'output versions are immutable; only status moves forward';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

revision: str = "0017"
down_revision: str | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outputs",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("output_type", sa.String(length=40), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("subject_type", sa.String(length=60), nullable=True),
        sa.Column("subject_id", sa.Uuid(), nullable=True),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("provenance", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], name=op.f("fk_outputs_project_id_projects")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outputs")),
    )
    op.create_index(op.f("ix_outputs_project_id"), "outputs", ["project_id"], unique=False)
    op.create_table(
        "output_versions",
        sa.Column("output_id", sa.Uuid(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("blocks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("change_reason", sa.Text(), nullable=True),
        sa.Column("approval_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["output_id"], ["outputs.id"], name=op.f("fk_output_versions_output_id_outputs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_output_versions")),
        sa.UniqueConstraint("output_id", "version_number", name=op.f("uq_output_versions_output_id")),
    )
    op.create_index(op.f("ix_output_versions_output_id"), "output_versions", ["output_id"], unique=False)
    op.create_index(op.f("ix_output_versions_status"), "output_versions", ["status"], unique=False)
    op.execute(PROTECT_VERSION)
    op.execute(
        "CREATE TRIGGER output_versions_immutable BEFORE UPDATE OR DELETE ON output_versions "
        "FOR EACH ROW EXECUTE FUNCTION protect_output_version()"
    )
    op.execute(
        "CREATE TRIGGER outputs_kept BEFORE DELETE ON outputs FOR EACH ROW EXECUTE FUNCTION keep_research_record()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS outputs_kept ON outputs")
    op.execute("DROP TRIGGER IF EXISTS output_versions_immutable ON output_versions")
    op.execute("DROP FUNCTION IF EXISTS protect_output_version()")
    op.drop_index(op.f("ix_output_versions_status"), table_name="output_versions")
    op.drop_index(op.f("ix_output_versions_output_id"), table_name="output_versions")
    op.drop_table("output_versions")
    op.drop_index(op.f("ix_outputs_project_id"), table_name="outputs")
    op.drop_table("outputs")
    # ### end Alembic commands ###
