"""Output integrity pipeline runs (append-only) and the edited flag on versions (FR-OUT-002, ADR-021).

Additive only: one table and one column with a default.

Revision ID: 0018
Revises: 0017
Create Date: 2026-09-24 22:42:50.133651
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0018"
down_revision: str | None = "0017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "output_integrity_runs",
        sa.Column("output_version_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("steps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("run_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["output_version_id"],
            ["output_versions.id"],
            name=op.f("fk_output_integrity_runs_output_version_id_output_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_output_integrity_runs")),
    )
    op.create_index(
        op.f("ix_output_integrity_runs_output_version_id"), "output_integrity_runs", ["output_version_id"], unique=False
    )
    op.add_column("output_versions", sa.Column("edited", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.execute(
        "CREATE TRIGGER output_integrity_runs_append_only BEFORE UPDATE OR DELETE ON output_integrity_runs "
        "FOR EACH ROW EXECUTE FUNCTION reject_mutation_of_append_only()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS output_integrity_runs_append_only ON output_integrity_runs")
    op.drop_column("output_versions", "edited")
    op.drop_index(op.f("ix_output_integrity_runs_output_version_id"), table_name="output_integrity_runs")
    op.drop_table("output_integrity_runs")
    # ### end Alembic commands ###
