"""Disclosure manifest for the selective cloud workspace (FR-CLOUD-003, FR-CLOUD-006, ADR-023).

Additive only: two new tables. Staged items are append-only; a staging keeps every column except its
status, which only moves ACTIVE -> DELETED/EXPIRED together with who removed it and why. BLOCKED is final.

Revision ID: 0019
Revises: 0018
Create Date: 2026-09-25 04:24:52.293651
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

PROTECT = """
CREATE OR REPLACE FUNCTION protect_workspace_staging() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'the disclosure manifest is kept and cannot be deleted';
    END IF;
    IF (to_jsonb(NEW) - 'status' - 'deleted_at' - 'deleted_by' - 'delete_reason')
            <> (to_jsonb(OLD) - 'status' - 'deleted_at' - 'deleted_by' - 'delete_reason')
        OR NOT (OLD.status = 'ACTIVE' AND NEW.status IN ('DELETED', 'EXPIRED'))
        OR NEW.deleted_at IS NULL THEN
        RAISE EXCEPTION 'the disclosure manifest is immutable; only an active staging can be deleted or expire';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
"""

revision: str = "0019"
down_revision: str | None = "0018"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "workspace_stagings",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("adapter", sa.String(length=40), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("sensitivity", sa.String(length=20), nullable=False),
        sa.Column("policy_decision", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("staged_by", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("delete_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_workspace_stagings_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_stagings")),
    )
    op.create_index(op.f("ix_workspace_stagings_expires_at"), "workspace_stagings", ["expires_at"], unique=False)
    op.create_index(op.f("ix_workspace_stagings_project_id"), "workspace_stagings", ["project_id"], unique=False)
    op.create_index(op.f("ix_workspace_stagings_status"), "workspace_stagings", ["status"], unique=False)
    op.create_table(
        "workspace_staged_items",
        sa.Column("staging_id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("byte_size", sa.Integer(), nullable=False),
        sa.Column("remote_ref", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["staging_id"],
            ["workspace_stagings.id"],
            name=op.f("fk_workspace_staged_items_staging_id_workspace_stagings"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_staged_items")),
    )
    op.create_index(
        op.f("ix_workspace_staged_items_staging_id"), "workspace_staged_items", ["staging_id"], unique=False
    )
    op.execute(PROTECT)
    op.execute(
        "CREATE TRIGGER workspace_stagings_protect BEFORE UPDATE OR DELETE ON workspace_stagings "
        "FOR EACH ROW EXECUTE FUNCTION protect_workspace_staging()"
    )
    op.execute(
        "CREATE TRIGGER workspace_staged_items_append_only BEFORE UPDATE OR DELETE ON workspace_staged_items "
        "FOR EACH ROW EXECUTE FUNCTION reject_mutation_of_append_only()"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS workspace_staged_items_append_only ON workspace_staged_items")
    op.execute("DROP TRIGGER IF EXISTS workspace_stagings_protect ON workspace_stagings")
    op.execute("DROP FUNCTION IF EXISTS protect_workspace_staging()")
    op.drop_index(op.f("ix_workspace_staged_items_staging_id"), table_name="workspace_staged_items")
    op.drop_table("workspace_staged_items")
    op.drop_index(op.f("ix_workspace_stagings_status"), table_name="workspace_stagings")
    op.drop_index(op.f("ix_workspace_stagings_project_id"), table_name="workspace_stagings")
    op.drop_index(op.f("ix_workspace_stagings_expires_at"), table_name="workspace_stagings")
    op.drop_table("workspace_stagings")
    # ### end Alembic commands ###
