"""Chunk embeddings for semantic retrieval (PRD §23, §61, ADR-025).

Additive only: one table of derived vectors, keyed by chunk and model, deleted with its chunk.

Revision ID: 0020
Revises: 0019
Create Date: 2026-09-25 10:50:37.192375
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "0020"
down_revision: str | None = "0019"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_chunk_embeddings",
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["source_chunks.id"],
            name=op.f("fk_source_chunk_embeddings_chunk_id_source_chunks"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("chunk_id", "model", name=op.f("pk_source_chunk_embeddings")),
    )
    op.create_index(op.f("ix_source_chunk_embeddings_model"), "source_chunk_embeddings", ["model"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_chunk_embeddings_model"), table_name="source_chunk_embeddings")
    op.drop_table("source_chunk_embeddings")
    # ### end Alembic commands ###
